name: Gradle Simulate

on:
    push:

jobs:
    Simulate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Init JDK
              uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: '17'
            - name: Set Execution Permissions
              run: chmod +x ./gradlew && chmod +x .github/run_sim_timeout.sh
            - name: Simulate Robot
              run: .github/run_sim_timeout.sh
